version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: sampledaploumentapp
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m